/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_Music */

#ifndef _Included_model_Music
#define _Included_model_Music
#ifdef __cplusplus
extern "C" {
#endif
#undef model_Music_MIN_PRIORITY
#define model_Music_MIN_PRIORITY 1L
#undef model_Music_NORM_PRIORITY
#define model_Music_NORM_PRIORITY 5L
#undef model_Music_MAX_PRIORITY
#define model_Music_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
